# If not running interactively, don't do anything
[[ $- != *i* ]] && return

### SHOPT ###
shopt -s autocd         # change to named directory
shopt -s cdspell        # autocorrects cd misspellings
shopt -s cmdhist        # save multi-line commands in history as single line
shopt -s histappend     # do not overwrite history
shopt -s expand_aliases # expand aliases
shopt -s checkwinsize   # checks term size when bash regains control
shopt -s globstar       # use ** for recursive wildcard

bind "set completion-ignore-case on"

### ENV ###
# History control
export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=1000
export HISTFILESIZE=2000

### PROMPT ###
# "<current directory> $ " all in green
export PS1=$'\[\033[1;32m\]\W $ \[\033[0m\]'

### ALIAS ###
alias  ..='cd ..'
alias ...='cd ../..'
alias  .3='cd ../../..'
alias  .4='cd ../../../..'
alias  .5='cd ../../../../..'

# Prefered format and colors
alias grep='grep --color=auto'
alias ls='ls --color=auto --group-directories-first -hv'
alias ip='ip --color=auto'
alias diff='diff --color=auto -u'
alias less='less -Ri'
alias df='df -hi'
alias ll='ls -l'
alias la='ls -lA'

# Better cat
alias cat='bat --theme="Visual Studio Dark+"'
alias icat='wezterm imgcat'

# Confirm before overwriting or deleting
alias rm='rm -iv'
alias mv='mv -iv'
alias cp='cp -iv'

### FUNCTIONS ###
function notes {
    local file=$(fd -tf -e md -e typ . ~/notes | fzf --preview "bat --plain --color=always {}")
    if [[ -n "$file" ]]; then
        pushd ~/notes >/dev/null && nvim "$file" && popd > /dev/null
    fi
}

# Run fastfetch on startup if:
#   - the command exists
#   - not running inside Vim or Neovim
#   - not running inside tmux or zellij
#   - not running inside SSH
if command -v fastfetch >/dev/null 2>&1 \
   && [ -z "${NVIM+x}" ] \
   && [ -z "${VIMRUNTIME+x}" ] \
   && [ -z "${TMUX+x}" ] \
   && [ -z "${ZELLIJ+x}" ] \
   && [ -z "${SSH_TTY+x}" ]; then
    fastfetch
fi
